name: Practice 1
defaults:
      run:
        working-directory: /practice1
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm ci
    - name: Run lint
      run: npm lint
  test: 
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm ci
    - name: Run test
      run: npm test
  deploy: 
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm ci
    - name: Run deploy
      run: npm deploy; echo "Deploying..."
  allActions:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm ci
    - name: Run Lint
      run: npm lint
    - name: Run Test
      run: npm test
    - name: Run Deploy
      run: npm deploy; echo "Deploying..."
